namespace LauncherShared;

public enum AppLanguage { French, English }

/// <summary>
/// Detecte la langue a utiliser pour tous les textes affiches par
/// LauncherGenerator (et, si besoin plus tard, UniversalSteamLauncher).
///
/// Source de verite : un fichier "lang.txt" ("fr" ou "en") depose a cote de
/// l'exe par l'installeur Inno Setup, en fonction de la langue choisie a
/// l'installation (voir la section [Code] de UniversalSteamLauncher.iss).
/// En dev (dotnet run, pas de lang.txt), on retombe sur la langue systeme.
/// </summary>
public static class AppLanguageProvider
{
    public static AppLanguage Current { get; } = Detect();

    private static AppLanguage Detect()
    {
        string langFile = Path.Combine(AppContext.BaseDirectory, "lang.txt");
        if (File.Exists(langFile))
        {
            string content = File.ReadAllText(langFile).Trim().ToLowerInvariant();
            if (content == "en") return AppLanguage.English;
            if (content == "fr") return AppLanguage.French;
        }

        return System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "fr"
            ? AppLanguage.French
            : AppLanguage.English;
    }
}

/// <summary>
/// Table de textes FR/EN. Get(cle, args) renvoie le texte dans la langue
/// courante (AppLanguageProvider.Current), avec String.Format si des args
/// sont passes. Une cle absente renvoie la cle elle-meme (facile a reperer
/// si un texte a ete oublie lors d'un ajout).
/// </summary>
public static class Strings
{
    public static string Get(string key, params object[] args)
    {
        var pair = Table.TryGetValue(key, out var v) ? v : (key, key);
        string template = AppLanguageProvider.Current == AppLanguage.French ? pair.Item1 : pair.Item2;
        return args.Length == 0 ? template : string.Format(template, args);
    }

    private static readonly Dictionary<string, (string fr, string en)> Table = new()
    {
        ["banner.title"] = (" Universal Steam Launcher", " Universal Steam Launcher"),
        ["banner.subtitle"] = (" Launcher Generator", " Launcher Generator"),
        ["banner.author"] = ("Created by Blinkixane", "Created by Blinkixane"),

        ["error.launcherNotFound.hint"] = (
            "Compile d'abord le projet UniversalSteamLauncher (Debug ou Release), puis relance ce generateur.",
            "Build the UniversalSteamLauncher project first (Debug or Release), then run this generator again."),

        ["prompt.name"] = ("Nom du jeu : ", "Game name: "),

        ["prompt.steamUri"] = (
            "Steam URL (ou juste l'ID rungameid) (trouvable en creeant un raccourci du jeu non steam sur le bureau (parametre du jeu -> gerer -> Creer un raccourci sur le bureau): ",
            "Steam URL (or just the rungameid ID) (found by creating a desktop shortcut for the non-Steam game: game settings -> Manage -> Create desktop shortcut): "),

        ["prompt.exePath"] = ("Chemin EXE du jeu : ", "Game EXE path: "),

        ["prompt.iconPath"] = (
            "Chemin icone .ico (optionnel, Entree = utilise l'exe du jeu) : ",
            ".ico icon path (optional, Enter = use the game's exe): "),

        ["aumid.searching"] = ("Recherche AUMID...", "Looking up AUMID..."),

        ["aumid.notFound.line1"] = (
            "AUMID introuvable automatiquement (le jeu n'apparait pas dans Get-StartApps).",
            "AUMID not found automatically (the game doesn't appear in Get-StartApps)."),
        ["aumid.notFound.line2"] = (
            "Pour Trouver facilement l'AUMID, lancez le jeu une fois ",
            "To easily find the AUMID, launch the game once "),
        ["aumid.notFound.line3"] = (
            "Puis executer le script PowerShell Get-Aumid.ps1 fourni dans le depot.",
            "Then run the Get-Aumid.ps1 PowerShell script included in the repo."),
        ["aumid.notFound.line4"] = (
            "Copiez l'AUMID trouve et collez le ci-dessous.",
            "Copy the AUMID you find and paste it below."),
        ["aumid.prompt"] = (
            "Entrer l'AUMID (Ex : Microsoft.AutoGenerated.{{...}}) : ",
            "Enter the AUMID (e.g. Microsoft.AutoGenerated.{{...}}): "),

        ["summary.title"] = ("Configuration :", "Configuration:"),
        ["summary.separator"] = ("----------------", "----------------"),
        ["summary.name"] = ("Nom      : {0}", "Name     : {0}"),
        ["summary.steam"] = ("Steam    : {0}", "Steam    : {0}"),
        ["summary.exe"] = ("EXE      : {0}", "EXE      : {0}"),
        ["summary.icon"] = ("Icone    : {0}", "Icon     : {0}"),
        ["summary.aumid"] = ("AUMID    : {0}", "AUMID    : {0}"),

        ["shortcut.creating"] = ("Creation du raccourci : {0}", "Creating shortcut: {0}"),
        ["shortcut.doneWithAumid"] = (
            "Raccourci cree avec AUMID applique.",
            "Shortcut created with AUMID applied."),
        ["shortcut.doneWithoutAumid"] = (
            "Raccourci cree sans AUMID (pas de regroupement possible avec la fenetre du jeu).",
            "Shortcut created without AUMID (icon grouping with the game window won't be possible)."),

        ["done.line1"] = (
            "Pret. Epingle manuellement le raccourci du bureau a la barre des taches",
            "Done. Pin the desktop shortcut to the taskbar manually"),
        ["done.line2"] = (
            "(clic droit -> Epingler a la barre des taches)",
            "(right-click -> Pin to taskbar)"),

        ["error.launcherNotFound"] = (
            "UniversalSteamLauncher.exe est introuvable, veuillez reinstaller le programme",
            "UniversalSteamLauncher.exe was not found, please reinstall the app"),
    };
}
