using System;
using System.IO;
using LauncherCore;

class Program
{
    // AUMID auto-generated of Genshin Impact
    const string GenshinAumid =
        "Microsoft.AutoGenerated.{964DC2A2-D045-9867-D3D8-2BB16268FE92}";

    static void Main(string[] args)
    {
        string lnkPath;

        if (args.Length > 0)
        {
            lnkPath = args[0];
        }
        else
        {
            lnkPath = @"C:\Users\euxan\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\GenshinSteamLauncher.lnk";
        }

        Console.WriteLine("Raccourci :");
        Console.WriteLine(lnkPath);
        Console.WriteLine();

        if (!File.Exists(lnkPath))
        {
            Console.WriteLine("ERREUR : raccourci introuvable.");
            Console.ReadKey();
            return;
        }

        try
        {
            bool rewritten = ShortcutAumidStore.WriteAumid(
                lnkPath,
                GenshinAumid);

            if (rewritten)
                Console.WriteLine("AUMID écrit avec succès.");
            else
                Console.WriteLine("Le raccourci possédait déjà le bon AUMID.");

            Console.WriteLine();

            string? current = ShortcutAumidStore.ReadAumid(lnkPath);

            Console.WriteLine("AUMID actuellement stocké :");
            Console.WriteLine(current ?? "(aucun)");
            Console.WriteLine();

            Console.WriteLine(current == GenshinAumid
                ? "Vérification OK."
                : "ATTENTION : l'AUMID ne correspond pas.");
        }
        catch (Exception ex)
        {
            Console.WriteLine("Erreur :");
            Console.WriteLine(ex);
        }

        Console.WriteLine();
        Console.WriteLine("Appuyez sur une touche pour quitter...");
        Console.ReadKey();
    }
}
