using System;
using LauncherCore;

class Program
{
    const string TargetAumid =
        "Microsoft.AutoGenerated.{964DC2A2-D045-9867-D3D8-2BB16268FE92}";

    static void Main(string[] args)
    {
        string processName = args.Length > 0
            ? args[0]
            : "GenshinImpact";

        Console.WriteLine($"Attente de la fenêtre de '{processName}'...");

        var proc = ProcessWindowWaiter.WaitForMainWindow(processName);

        if (proc == null)
        {
            Console.WriteLine("Fenêtre jamais apparue, abandon.");
            return;
        }

        Console.WriteLine($"Trouvée : PID {proc.Id}, hwnd = {proc.MainWindowHandle}");

        var result = AumidWindowTagger.Apply(
            proc.MainWindowHandle,
            TargetAumid,
            out var err);

        Console.WriteLine($"Résultat : {result}");

        if (!string.IsNullOrWhiteSpace(err))
            Console.WriteLine($"Détail : {err}");

        if (result == AumidWindowTagger.TagResult.Success)
        {
            string? current = AumidWindowTagger.Read(proc.MainWindowHandle);

            Console.WriteLine("AUMID relu : " + (current ?? "(aucun)"));

            if (current == TargetAumid)
                Console.WriteLine("Vérification OK.");
            else
                Console.WriteLine("ATTENTION : l'AUMID relu ne correspond pas.");
        }
    }
}
